name: James Zhao
title: James Zhao
description: The people who are crazy enough to think they can change the world are the ones who do.
meta_description: "James Zhao"
image: /assets/images/profile.png

markdown: kramdown
highlighter: rouge

baseurl: '/'

logo: false
paginate: 15
permalink: /:title

username: James-Zhao
# Details for the RSS feed generator
url:            'James-Zhao.github.io'
author:         'James Zhao'

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
